In [2]:
import numpy as np

In [8]:
x=np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
np.random.shuffle(x)
print(x)

[4 3 5 8 1 2 0 9 6 7]


In [12]:
x=np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [13]:
for func in [x.min,x.max,x.sum,x.prod,x.mean,x.std,x.var]:
    print(func.__name__,'=',func())

min = 1
max = 4
sum = 10
prod = 24
mean = 2.5
std = 1.118033988749895
var = 1.25


In [16]:
a=np.arange(5)
print(a)
a=np.arange(5).reshape(1,1,5)
print(a)

[0 1 2 3 4]
[[[0 1 2 3 4]]]


In [20]:
b=np.array([10,20,30,40,50])

In [21]:
print(a+b)

[[[10 21 32 43 54]]]


In [22]:
print(np.empty(5))

[4.94e-323 1.04e-322 1.58e-322 2.12e-322 2.67e-322]


In [25]:
print(np.empty_like(x))

[[4612248968380809216 4598175219545276416]
 [4598175219545276416 4612248968380809216]]


In [26]:
print(np.zeros_like(x))

[[0 0]
 [0 0]]
