In [1]:
import numpy as np

import matplotlib.pyplot as plt
import pandas as pd

from sklearn import datasets

from sklearn.datasets import load_iris
# from sklearn.datasets import load_digits
# from sklearn.datasets import fetch_olivetti_faces
# from sklearn.neural_network import MLPClassifier
# from sklearn.metrics import accuracy_score
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import confusion_matrix
# from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier

In [2]:
iris = load_iris()
X, y = iris.data, iris.target

clf = KNeighborsClassifier()

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.5,random_state=123)
print("Labels for training and testing data")
print(y_train)
print(y_test)

Labels for training and testing data
[1 1 0 2 2 0 0 1 1 2 0 0 1 0 1 2 0 2 0 0 1 0 0 1 2 1 1 1 0 0 1 2 0 0 1 1 1
 2 1 1 1 2 0 0 1 2 2 2 2 0 1 0 1 1 0 1 2 1 2 2 0 1 0 2 2 1 1 2 2 1 0 1 1 2
 2]
[1 2 2 1 0 2 1 0 0 1 2 0 1 2 2 2 0 0 1 0 0 2 0 2 0 0 0 2 2 0 2 2 0 0 1 1 2
 0 0 1 1 0 2 2 2 2 2 1 0 0 2 0 0 1 1 1 1 2 1 2 0 2 1 0 0 2 1 2 2 0 1 1 2 0
 2]


In [4]:
labels, counts = np.unique(y, return_counts=True)
print(counts / float(len(y)))

[0.33333333 0.33333333 0.33333333]


In [5]:
labels, counts = np.unique(y_train, return_counts=True)
print(counts / float(len(y_train)))

[0.30666667 0.4        0.29333333]


In [6]:
labels, counts = np.unique(y_test, return_counts=True)
print(counts / float(len(y_test)))

[0.36       0.26666667 0.37333333]
