In [1]:
import torch

In [2]:
x=torch.tensor([5,3])
y=torch.tensor([2,1])
print(x*y)

tensor([10,  3])


In [4]:
x=torch.zeros([2,5])
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [5]:
x.shape

torch.Size([2, 5])

In [6]:
y=torch.rand([2,5])
y

tensor([[0.4318, 0.8726, 0.0616, 0.4046, 0.0088],
        [0.7206, 0.4721, 0.0269, 0.9713, 0.5272]])

In [8]:
y=y.view([1,10])
y

tensor([[0.4318, 0.8726, 0.0616, 0.4046, 0.0088, 0.7206, 0.4721, 0.0269, 0.9713,
         0.5272]])